version: '3.4'

services:
  mongo:
    ports:
      - 27017:27017

  sqlserver:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433

  cache:
    ports:
      - 127.0.0.1:6379:6379
  
  # um
  um.users.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__UserContextConnection=Server=sqlserver;Database=TS_Users;User Id=sa;Password=Pass@word;Integrated Security=true;Encrypt=False;Trusted_Connection=False
    ports:
      - 4101:80
  
  um.identity.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__IdentityDatabase=mongodb://mongo/TS_IdentityServer
      - ConnectionStrings__Issuer=http://localhost:4102
      - ConnectionStrings__Authority=http://localhost:4102
      - ConnectionStrings__UsersService=http://um.users.service
      - ConnectionStrings__UserTasksService=http://um.usertasks.service
    ports:
      - 4102:80

  um.usertasks.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__UserTasksDatabase=mongodb://mongo/TS_UserTasks
    ports:
      - 4103:80

  bs.apigateway.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - JwtOptions__Issuers__0=http://localhost:4102
      - ConnectionStrings__Authority=http://um.identity.service
    ports:
      - 4104:80