version: '3.4'

services:
  mongo:
    ports:
      - 27017:27017

  sqlserver:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433

  cache:
    ports:
      - 127.0.0.1:6379:6379
  
  # um
  um.users.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 4101:80
  
  um.identity.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 4102:80

  um.usertasks.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Issuer=http://localhost:4102
      - ConnectionStrings__UsersService=http://localhost:4101
      - ConnectionStrings__UserTasksService=http://localhost:4102
    ports:
      - 4103:80

  bs.apigateway.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 4104:80